os:
    Windows:
    Linux:
    Macos:
arch: [x86_64]
compiler:
    gcc: &gcc
        version: ["9.2"]
        libcxx: [libstdc++]
    Visual Studio: &visual_studio
        version: ["16"]
    clang:
        version: ["10"]
    apple-clang:
        version: ["11.0"]
build_type: [Release]
