name: Generate graph

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install graphviz
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Compute graph
      run: |
        python cci_map/__init__.py --add-drafts --threads 1
    - name: Generate PDF/PNG from graph
      run: |
        mkdir _output
        dot -Tpdf -Gdpi=300 _working_dir/graphviz.dot > _output/graph.pdf
        dot -Tpng -Gdpi=300 _working_dir/graphviz.dot > _output/graph.png
    - name: Upload graph
      uses: actions/upload-artifact@v1
      with:
        name: Graph
        path: _output/*
    - name: Deploy to GitHub pages
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: _output
        GH_PAT: ${{ secrets.GITHUB_TOKEN }}
