name: Generate graph

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install graphviz
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Compute graph
      run: |
        python cci_map/__init__.py --add-drafts --threads 1
    - name: Generate PDF/PNG from graph
      run: |
        mkdir _output
        dot -Tpdf -Gdpi=300 _working_dir/graphviz.dot > _output/graph.pdf
        dot -Tpng -Gdpi=300 _working_dir/graphviz.dot > _output/graph.png

    - name: Upload graph-pdf
      uses: actions/upload-artifact@v1
      with:
        name: graph-pdf
        path: _output/graph.pdf
    - name: Upload graph-png
      uses: actions/upload-artifact@v1
      with:
        name: graph-png
        path: _output/graph.png

    - name: Deploy to gh-pages
      run: |
        cd _output
        git init .
        git checkout -b gh-pages
        git add .
        git config user.email "actions@github.com"
        git config user.name "GitHub actions"
        git commit -m "Automatic from Github actions"
        git remote add origin-pages https://${{ secrets.GH_TOKEN }}@github.com/jgsogo/conan-center-index-graph.git > /dev/null 2>&1
        git push --quiet --force --set-upstream origin-pages gh-pages 
